name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pre-commit & dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pre-commit install --install-hooks
          pre-commit run --all-files

      - name: Run tests (placeholder)
        run: |
          echo "No tests yet"

      - name: Build Docker images
        run: |
          docker compose build --progress plain 