name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set up Node.js (for pyright)
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          # Install all project dependencies
          pip install -r chat-service/requirements.txt
          pip install -r etl_job/requirements.txt
          # Install pre-commit hooks
          pre-commit install --install-hooks

      - name: Run pre-commit checks
        run: |
          pre-commit run --all-files

      - name: Run tests
        run: |
          pytest tests/ -q

      - name: Build Docker images
        run: |
          docker compose build --progress plain 